version: "3.3"
services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    restart: always
    depends_on:
        - api
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  api:
    depends_on: 
      - db
    env_file: 
      - docker.env
    image: mooretrev/react-personal-website
    restart: always
    ports:
      - 9000:9000
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

volumes:
  mongodb:
