version: "3.3"
services:
  backend:
    env_file: 
      - api/docker.env
    build: .
    ports:
      - "9000:9000"
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
