services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse-proxy
    restart: always
    depends_on:
        - api
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  api:
    depends_on:
      - db
    env_file:
      - docker.env
    container_name: api
    restart: always
    image: mooretrev/react-personal-website
    ports:
      - 9000:9000
  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

volumes:
  mongodb:
