version: "3.3"
services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
        - api
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
  api:
    depends_on: 
      - db
    env_file: 
      - docker.env
    build: 
      .
    ports:
      - 9000:9000
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
